# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx-ssl-proxy
  labels:
    name: nginx
    role: ssl-proxy
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
    spec:
      containers:
      - name: nginx-ssl-proxy
        image: gcr.io/cloud-solutions-images/nginx-ssl-proxy:master-cc00da0 
        command:
        - /bin/bash
        - /usr/bin/start.sh
        env:
        - name: SERVICE_HOST_ENV_NAME
          value: JENKINS_SERVICE_HOST
        - name: SERVICE_PORT_ENV_NAME
          value: JENKINS_SERVICE_PORT_UI
        - name: ENABLE_BASIC_AUTH
          value: 'true'
        ports:
        - name: ssl-proxy-http
          containerPort: 80
        - name: ssl-proxy-https
          containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: ssl-proxy-secret
